#include "ps1recomp/psyq_hle_allowlist.h"

#include <unordered_set>

namespace ps1recomp {

namespace {
/// Every key `ps1Runtime/src/psyq/*.cpp` hands to `psyq_register`, including
/// the ones `registerAllPrefixes` fans out across library prefixes.
///
/// This is the analyzer's only view of what the runtime can actually answer
/// for. It has to stay in step with the registry: a name listed here that
/// nobody registers turns into a fatal dispatch the first time the game calls
/// it, and a registered name missing from here loses its HLE and gets
/// recompiled instead -- correct, but slower and without the shortcut.
const std::unordered_set<std::string>& implementedNames() {
    static const std::unordered_set<std::string> kNames = {
    "libapi_ChangeClearPAD",
    "libapi_ChangeClearRCnt",
    "libapi_CloseEvent",
    "libapi_DeliverEvent",
    "libapi_DisableEvent",
    "libapi_EnableEvent",
    "libapi_EnterCriticalSection",
    "libapi_ExitCriticalSection",
    "libapi_GPU_cw",
    "libapi_HookEntryInt",
    "libapi_InitHeap",
    "libapi_InitPAD2",
    "libapi_OpenEvent",
    "libapi_ReturnFromException",
    "libapi_SetRCnt",
    "libapi_StartPAD2",
    "libapi_StartRCnt",
    "libapi_StopPAD2",
    "libapi_StopRCnt",
    "libapi_TestEvent",
    "libapi__96_remove",
    "libapi__bu_init",
    "libapi__memmove",
    "libapi_abs",
    "libapi_atoi",
    "libapi_close",
    "libapi_erase",
    "libapi_firstfile2",
    "libapi_format",
    "libapi_labs",
    "libapi_memcmp",
    "libapi_memcpy",
    "libapi_memmove",
    "libapi_memset",
    "libapi_nextfile",
    "libapi_open",
    "libapi_printf",
    "libapi_rand",
    "libapi_read",
    "libapi_sprintf",
    "libapi_srand",
    "libapi_strcat",
    "libapi_strcmp",
    "libapi_strcpy",
    "libapi_strlen",
    "libapi_strncmp",
    "libapi_strncpy",
    "libapi_write",
    "libc__memmove",
    "libc_abs",
    "libc_atoi",
    "libc_labs",
    "libc_memcmp",
    "libc_memcpy",
    "libc_memmove",
    "libc_memset",
    "libc_printf",
    "libc_rand",
    "libc_sprintf",
    "libc_srand",
    "libc_strcat",
    "libc_strcmp",
    "libc_strcpy",
    "libc_strlen",
    "libc_strncmp",
    "libc_strncpy",
    "libcd_CD_datasync",
    "libcd_CdControl",
    "libcd_CdControlF",
    "libcd_CdDataCallback",
    "libcd_CdGetSector",
    "libcd_CdInit",
    "libcd_CdMix",
    "libcd_CdRead",
    "libcd_CdReadBreak",
    "libcd_CdReadCallback",
    "libcd_CdReadSync",
    "libcd_CdReady",
    "libcd_CdReadyCallback",
    "libcd_CdSync",
    "libcd_StCdInterrupt2",
    "libcd_StSetMask",
    "libcd_abs",
    "libcd_atoi",
    "libcd_labs",
    "libcd_memcmp",
    "libcd_memcpy",
    "libcd_memmove",
    "libcd_memset",
    "libcd_printf",
    "libcd_rand",
    "libcd_sprintf",
    "libcd_srand",
    "libcd_strcat",
    "libcd_strcmp",
    "libcd_strcpy",
    "libcd_strlen",
    "libcd_strncmp",
    "libcd_strncpy",
    "libetc_CheckCallback",
    "libetc_DMACallback",
    "libetc_GetIntrMask",
    "libetc_GetVideoMode",
    "libetc_InterruptCallback",
    "libetc_PadGetState",
    "libetc_PadInit",
    "libetc_PadInitDirect",
    "libetc_PadRead",
    "libetc_PadStartCom",
    "libetc_PadStopCom",
    "libetc_ResetCallback",
    "libetc_RestartCallback",
    "libetc_SetIntrMask",
    "libetc_SetVideoMode",
    "libetc_StopCallback",
    "libetc_VSync",
    "libetc_VSyncCallback",
    "libetc_VSyncCallbacks",
    "libetc_abs",
    "libetc_atoi",
    "libetc_labs",
    "libetc_memcmp",
    "libetc_memcpy",
    "libetc_memmove",
    "libetc_memset",
    "libetc_printf",
    "libetc_rand",
    "libetc_restartIntr",
    "libetc_sprintf",
    "libetc_srand",
    "libetc_startIntr",
    "libetc_stopIntr",
    "libetc_strcat",
    "libetc_strcmp",
    "libetc_strcpy",
    "libetc_strlen",
    "libetc_strncmp",
    "libetc_strncpy",
    "libgpu_ClearImage",
    "libgpu_DrawOTag",
    "libgpu_DrawPrim",
    "libgpu_DrawSync",
    "libgpu_DrawSyncCallback",
    "libgpu_FntFlush",
    "libgpu_FntLoad",
    "libgpu_FntOpen",
    "libgpu_FntPrint",
    "libgpu_FntSystem",
    "libgpu_LoadImage",
    "libgpu_MoveImage",
    "libgpu_PutDispEnv",
    "libgpu_PutDrawEnv",
    "libgpu_ResetGraph",
    "libgpu_SetDispMask",
    "libgpu_SetDumpFnt",
    "libgpu_StoreImage",
    "libgpu__addque",
    "libgpu__addque2",
    "libgpu__clr",
    "libgpu__drs",
    "libgpu__dws",
    "libgpu__reset",
    "libgpu_abs",
    "libgpu_atoi",
    "libgpu_checkRECT",
    "libgpu_labs",
    "libgpu_memcmp",
    "libgpu_memcpy",
    "libgpu_memmove",
    "libgpu_memset",
    "libgpu_printf",
    "libgpu_rand",
    "libgpu_sprintf",
    "libgpu_srand",
    "libgpu_strcat",
    "libgpu_strcmp",
    "libgpu_strcpy",
    "libgpu_strlen",
    "libgpu_strncmp",
    "libgpu_strncpy",
    "libgs_GsDefDispBuff",
    "libgs_GsInitGraph",
    "libgs_GsSetWorkBase",
    "libgs_GsSortClear",
    "libsn_abs",
    "libsn_atoi",
    "libsn_labs",
    "libsn_memcmp",
    "libsn_memcpy",
    "libsn_memmove",
    "libsn_memset",
    "libsn_printf",
    "libsn_rand",
    "libsn_sprintf",
    "libsn_srand",
    "libsn_strcat",
    "libsn_strcmp",
    "libsn_strcpy",
    "libsn_strlen",
    "libsn_strncmp",
    "libsn_strncpy",
    };
    return kNames;
}
} // namespace

bool psyqHleIsImplemented(const std::string& name) {
    return implementedNames().count(name) != 0;
}

} // namespace ps1recomp
