// ps1Runtime -- PS1 Hardware Simulation Runtime
// Full system integration: CPU, GPU, SPU, CD-ROM, DMA, Input, MDEC, Timers
// Game code runs in separate thread; main thread handles SDL events + rendering

#include "runtime/ps1_runtime_macros.h"
#include <SDL2/SDL.h>
#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <exception>
#include <filesystem>
#include <fmt/format.h>
#include <iostream>
#include <ps1recomp/elf_parser.h>
#include <runtime/bios/bios.h>
#include <runtime/psyq/psyq_hle.h>
#include <runtime/psyq/psyq_registry.h>
#include <runtime/psyq/psyq_state.h>
#include <runtime/cdrom/cdrom_controller.h>
#include <runtime/cdrom/virtual_fs.h>
#include <runtime/cpu_context.h>
#include <runtime/dma/dma.h>
#include <runtime/emuptr.h>
#include <runtime/gpu/gpu.h>
#include <runtime/gpu/renderer_opengl.h>
#include <runtime/input/input.h>
#include <runtime/mdec/mdec.h>
#include <runtime/memory.h>
#include <runtime/metrics.h>
#include <runtime/spu/spu.h>
#include <runtime/timers/timers.h>
#include <string>
#include <thread>
#include <toml.hpp>
#include <vector>

// SDL2 Audio Callback
static ps1::spu::SPU *g_spu = nullptr;

// Forward declaration -- generated by ps1Recomp in recompiled_out.cpp
extern void recomp_init_dispatch_table();

static void audioCallback(void * /*userdata*/, uint8_t *stream, int len) {
  if (!g_spu) {
    std::memset(stream, 0, len);
    return;
  }
  uint32_t numSamples = len / (2 * sizeof(int16_t)); // stereo S16
  g_spu->generateSamples(reinterpret_cast<int16_t *>(stream), numSamples);
}

// SDL2 Key Mapping
static void mapKeyToButton(SDL_Keycode key, ps1::input::InputController &input,
                           bool pressed) {
  using namespace ps1::input;
  uint16_t btn = 0;
  switch (key) {
  case SDLK_UP:
    btn = BTN_UP;
    break;
  case SDLK_DOWN:
    btn = BTN_DOWN;
    break;
  case SDLK_LEFT:
    btn = BTN_LEFT;
    break;
  case SDLK_RIGHT:
    btn = BTN_RIGHT;
    break;
  case SDLK_z:
    btn = BTN_CROSS;
    break;
  case SDLK_x:
    btn = BTN_CIRCLE;
    break;
  case SDLK_a:
    btn = BTN_SQUARE;
    break;
  case SDLK_s:
    btn = BTN_TRIANGLE;
    break;
  case SDLK_q:
    btn = BTN_L1;
    break;
  case SDLK_w:
    btn = BTN_R1;
    break;
  case SDLK_e:
    btn = BTN_L2;
    break;
  case SDLK_r:
    btn = BTN_R2;
    break;
  case SDLK_RETURN:
    btn = BTN_START;
    break;
  case SDLK_RSHIFT:
  case SDLK_BACKSPACE:
    btn = BTN_SELECT;
    break;
  default:
    return;
  }
  if (pressed)
    input.press(btn, 0);
  else
    input.release(btn, 0);
}

// Constants
static constexpr uint32_t CPU_CLOCK = 33868800;              // 33.8688 MHz
static constexpr uint32_t CYCLES_PER_FRAME = CPU_CLOCK / 60; // ~564480
static constexpr uint32_t CYCLES_PER_SCANLINE = 3413; // ~3413 cycles per hblank
static constexpr uint32_t SCANLINES_PER_FRAME = 263;  // NTSC

// SIGTERM/SIGINT raises this so `tools/smoke_test.py` (and `timeout`) can
// stop the runtime gracefully -- giving the main loop a chance to dump VRAM
// before the OS reaps us.
static volatile std::sig_atomic_t g_shutdown_requested = 0;
static void onTerminate(int) { g_shutdown_requested = 1; }

// Serialize full 1024x512 VRAM (ABGR1555) as a P6 PPM at `path`.
// Used by tools/smoke_test.py as the regression contract for game bring-up.
static bool dumpVramPpm(const ps1::gpu::GPU &gpu, const char *path) {
  std::FILE *f = std::fopen(path, "wb");
  if (!f) {
    fmt::print(stderr, "[VRAM-DUMP] open failed: {}\n", path);
    return false;
  }
  constexpr uint32_t W = ps1::gpu::GPU::VRAM_WIDTH;
  constexpr uint32_t H = ps1::gpu::GPU::VRAM_HEIGHT;
  std::fprintf(f, "P6\n%u %u\n255\n", W, H);
  const ps1::gpu::Color16 *vram = gpu.getVRAM();
  std::vector<uint8_t> row(W * 3);
  uint64_t nonZero = 0;
  for (uint32_t y = 0; y < H; ++y) {
    for (uint32_t x = 0; x < W; ++x) {
      uint16_t p = vram[y * W + x].raw;
      row[x * 3 + 0] = static_cast<uint8_t>((p & 0x1F) << 3);
      row[x * 3 + 1] = static_cast<uint8_t>(((p >> 5) & 0x1F) << 3);
      row[x * 3 + 2] = static_cast<uint8_t>(((p >> 10) & 0x1F) << 3);
      if (p != 0)
        ++nonZero;
    }
    std::fwrite(row.data(), 1, row.size(), f);
  }
  std::fclose(f);
  ps1::metrics::count("vram_dump.written");
  ps1::metrics::setState("vram_dump.nonzero_pixels",
                         static_cast<int64_t>(nonZero));
  fmt::print("[VRAM-DUMP] wrote {} ({}x{}), {} non-zero pixels\n", path, W, H,
             nonZero);
  return true;
}

int main(int argc, char *argv[]) {
  if (argc < 2) {
    std::cerr << "Usage: ps1Runtime <ps1_elf_or_iso> [disc_image] [--config "
                 "game.toml]\n"
              << "       ps1Runtime --config game.toml\n";
    return 1;
  }

  std::signal(SIGTERM, onTerminate);
  std::signal(SIGINT, onTerminate);

  // Parse arguments: support --config flag anywhere
  std::string input_path;
  std::string explicit_disc_path;
  std::string config_path;
  for (int i = 1; i < argc; i++) {
    if (std::string(argv[i]) == "--config" && i + 1 < argc) {
      config_path = argv[++i];
    } else if (input_path.empty()) {
      input_path = argv[i];
    } else if (explicit_disc_path.empty()) {
      explicit_disc_path = argv[i];
    }
  }

  // If only a TOML config is provided, read paths from it
  if (input_path.empty() && !config_path.empty()) {
    try {
      auto cfg = toml::parse(config_path);
      if (cfg.contains("disc")) {
        auto &disc = toml::find(cfg, "disc");
        if (disc.contains("exe_path"))
          input_path = toml::find<std::string>(disc, "exe_path");
        if (disc.contains("cue_path"))
          explicit_disc_path = toml::find<std::string>(disc, "cue_path");
      }
    } catch (const std::exception &e) {
      fmt::print(stderr, "Failed to parse config: {}\n", e.what());
      return 1;
    }
  }
  if (input_path.empty()) {
    std::cerr << "No ELF/EXE path provided (via argument or --config)\n";
    return 1;
  }
  fmt::print("ps1Runtime -- PS1 Hardware Simulation (Full Integration)\n");

  // Initialize all hardware subsystems

  // Core
  ps1::Memory memory;
  ps1::gpu::GPU gpu;
  ps1::spu::SPU spu;
  ps1::DMA dma;
  ps1::InterruptController irqCtrl;
  ps1::Timers timers;
  ps1::input::InputController input;
  ps1::mdec::MDEC mdec;
  ps1::cdrom::CdromController cdromCtrl;
  ps1::cdrom::VirtualFs fs;

  // Bind emuptr<T> to this Memory instance so hand-written HLE bodies
  // (psyq_hle.cpp etc.) resolve PS1 addresses through the live RAM buffer.
  ps1::emuptr_set_ram(memory.ramPtr());

  // Wire Memory I/O routing
  memory.setGPU(&gpu);
  memory.setSPU(&spu);
  memory.setDMA(&dma);
  memory.setCDROM(&cdromCtrl);
  memory.setInput(&input);
  memory.setMDEC(&mdec);
  memory.setTimers(&timers);
  memory.setInterruptController(&irqCtrl);

  // Wire DMA to devices
  dma.setMemory(&memory);
  dma.setGPU(&gpu);
  dma.setSPU(&spu);
  dma.setCDROM(&cdromCtrl);
  dma.setMDEC(&mdec);

  // Wire CDROM to VirtualFS
  cdromCtrl.attachVirtualFs(&fs);

  // Wire XA-ADPCM from CDROM -> SPU
  cdromCtrl.setXaCallback([&spu](const int16_t *samples, uint32_t count) {
    spu.pushXaSamples(samples, count);
  });

  // CPU Context
  recomp_context ctx;
  ctx.reset();
  ctx.mem = &memory;
  // Initialize Stack Pointer ($sp / r29) to top of 2MB Main RAM (KSEG0)
  ctx.r[29] = 0x801FFFF0;

  // BIOS
  ps1::bios::Bios bios(ctx, fs, memory);
  ctx.bios = &bios;
  bios.setGPU(&gpu);
  bios.setInputController(&input);
  bios.setCdromController(&cdromCtrl);
  bios.setDma(&dma);

  // Enable display (GP1 0x03, val=0): mirrors what the real BIOS does during boot.
  // reset() leaves bit 23 = 1 (display off) per hardware spec.
  gpu.writeGP1(0x03000000);

  // PsyQ HLE layer wiring
  // Phase 2 (2.1 .. 2.4) moved every per-game BSS address into the
  // process-wide `psyq_state()` singleton.  All HleConfig now carries are
  // the GP0/GP1 writers and a callback drain hook -- no addresses.
  {
    ps1::psyq::HleConfig hleCfg;
    hleCfg.drainCallbacks      = [&bios]() { bios.drainPendingCallbacks(); };
    hleCfg.writeGP0            = [&gpu](uint32_t w) { gpu.writeGP0(w); };
    hleCfg.writeGP1            = [&gpu](uint32_t w) { gpu.writeGP1(w); };
    hleCfg.deliverVBlankEvent  = [&bios]() { bios.triggerVBlankEvent(); };
    ps1::psyq::configure(hleCfg);
    psyq_registry_init_defaults();
    psyq_register_rayman_boot();
  }

  // Wire CDROM interrupt callback -> BIOS cross-thread queue (Phase 3.3).
  // The callback fires from `cdromCtrl.tick()` on the SDL render thread AND
  // from `cdromCtrl.writeRegister()` on the game thread -- calling
  // `triggerCdromEvent` directly from the SDL thread races on event-system
  // state with the game thread.  Push onto a mutex-protected queue instead;
  // `drainCdromEventQueue` pops and dispatches on the game thread (from
  // `drainPendingCallbacks` and `hle_libcd_CdSync`).
  cdromCtrl.setInterruptCallback(
      [&bios](uint8_t intType) { bios.queueCdromEvent(intType); });

  // Initialize SDL2

  if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_GAMECONTROLLER) < 0) {
    fmt::print(stderr, "SDL_Init failed: {}\n", SDL_GetError());
    return 1;
  }

  // Initialize renderer (creates window + OpenGL context)
  ps1::gpu::RendererOpenGL renderer(gpu);
  if (!renderer.init("ps1Recomp")) {
    fmt::print(stderr, "Failed to initialize OpenGL renderer!\n");
    SDL_Quit();
    return 1;
  }

  // SDL2 Audio
  g_spu = &spu;
  SDL_AudioSpec desired{}, obtained{};
  desired.freq = 44100;
  desired.format = AUDIO_S16SYS;
  desired.channels = 2;
  desired.samples = 1024;
  desired.callback = audioCallback;

  SDL_AudioDeviceID audioDevice =
      SDL_OpenAudioDevice(nullptr, 0, &desired, &obtained, 0);
  if (audioDevice > 0) {
    SDL_PauseAudioDevice(audioDevice, 0); // Start playback
    fmt::print("[Audio] SDL2 audio: {}Hz, {} ch, {} samples/buffer\n",
               obtained.freq, obtained.channels, obtained.samples);
  } else {
    fmt::print(stderr, "[Audio] Warning: could not open audio: {}\n",
               SDL_GetError());
  }

  // SDL2 GameController
  SDL_GameController *gamepad = nullptr;
  for (int i = 0; i < SDL_NumJoysticks(); i++) {
    if (SDL_IsGameController(i)) {
      gamepad = SDL_GameControllerOpen(i);
      if (gamepad) {
        fmt::print("[Input] GameController: {}\n",
                   SDL_GameControllerName(gamepad));
        break;
      }
    }
  }

  // Load ELF or ISO

  ps1recomp::ElfParser parser;
  if (!parser.load(input_path)) {
    fmt::print(stderr, "Failed to load ELF: {}\n", parser.getError());
    renderer.destroy();
    SDL_Quit();
    return 1;
  }

  // Auto-load corresponding Disc Image if running a extracted .boot.exe
  if (!explicit_disc_path.empty()) {
    // Disc image was explicitly provided as first argument
    if (fs.loadDisc(explicit_disc_path)) {
      fmt::print("[CDROM] Mounted disc image: {}\n", explicit_disc_path);
    } else {
      fmt::print(stderr, "[CDROM] WARNING: Could not mount disc image: {}\n",
                 explicit_disc_path);
    }
  } else {
    std::string disc_path = input_path;
    if (disc_path.ends_with(".boot.exe")) {
      disc_path =
          disc_path.substr(0, disc_path.length() - 9); // strip ".boot.exe"
      if (fs.loadDisc(disc_path)) {
        fmt::print("[CDROM] Automatically mounted disc image: {}\n", disc_path);
      } else {
        fmt::print(
            stderr,
            "[CDROM] WARNING: Could not mount corresponding disc image: {}\n",
            disc_path);
      }
    } else if (disc_path.ends_with(".bin") || disc_path.ends_with(".cue")) {
      if (fs.loadDisc(disc_path)) {
        fmt::print("[CDROM] Mounted disc image: {}\n", disc_path);
      }
    }
  }

  auto sections = parser.getSections();
  int loaded_sections = 0;
  for (const auto &sec : sections) {
    if ((sec.type == ps1recomp::SectionType::Text ||
         sec.type == ps1recomp::SectionType::Data) &&
        sec.data != nullptr) {
      uint32_t phys = ps1::Memory::toPhysical(sec.vaddr);
      if (phys < ps1::Memory::RAM_SIZE) {
        std::memcpy(memory.ramPtr() + phys, sec.data, sec.size);
        loaded_sections++;
      }
    }
  }
  fmt::print("Loaded {} sections into PS1 memory.\n", loaded_sections);

  // Apply [memory_init] pre-initialization
  // Some games need specific PS1 RAM locations pre-initialized before the
  // game code runs (e.g., PsyQ BSS pointer tables that CdInit would normally
  // set up but can't due to bootstrap timing in the recompiled environment).
  if (!config_path.empty()) {
    try {
      auto cfg = toml::parse(config_path);
      if (cfg.contains("memory_init")) {
        auto &mi = toml::find(cfg, "memory_init");
        if (mi.is_table()) {
          for (const auto &[key, val] : mi.as_table()) {
            uint32_t addr = std::strtoul(key.c_str(), nullptr, 0);
            uint32_t data = 0;
            if (val.is_integer()) {
              data = static_cast<uint32_t>(val.as_integer());
            } else if (val.is_string()) {
              data = std::strtoul(val.as_string().c_str(), nullptr, 0);
            }
            uint32_t phys = ps1::Memory::toPhysical(addr);
            if (phys + 4 <= ps1::Memory::RAM_SIZE) {
              memory.write32(addr, data);
              fmt::print("[memory_init] 0x{:08X} = 0x{:08X}\n", addr, data);
            } else {
              fmt::print(stderr,
                         "[memory_init] WARN: address 0x{:08X} out of RAM range\n",
                         addr);
            }
          }
        }
      }
    } catch (const std::exception &e) {
      fmt::print(stderr, "[WARN] Failed to read memory_init from config: {}\n",
                 e.what());
    }
  }

  // Main Emulation Loop
  // Game code runs in a separate thread (it never returns).
  // Main thread handles SDL events + hardware ticking + rendering.

  uint32_t entryPoint = parser.getEntryPoint();
  fmt::print("Starting emulation... Entry Point: 0x{:08X}\n", entryPoint);

  // DEBUG: verify binary data integrity at known vtable addresses
  {
    uint32_t dbgAddrs[] = {0x800549BC, 0x8005499C, 0x800549A4, 0x800549A8};
    for (auto a : dbgAddrs) {
      uint32_t phys = ps1::Memory::toPhysical(a);
      if (phys + 4 <= ps1::Memory::RAM_SIZE) {
        uint32_t val = memory.read32(a);
        fmt::print("[DBG] 0x{:08X} = 0x{:08X}\n", a, val);
      }
    }
  }
  std::atomic<bool> gameRunning{true};
  // `gameFinished` = "shutdown requested" (set by main or game thread)
  // `gameThreadDone` = "game thread lambda has returned" (set only by game
  // thread). Splitting these avoids the UAF in shutdown: previously the
  // cleanup code set `gameFinished` to request shutdown, then waited
  // `while (!gameFinished)` -- which already returned true the instant after
  // the request -- so the wait exited immediately and the still-running
  // game thread was detach()ed, leaving it racing with `Bios::~Bios()`
  // destructing `cdEventQueue_`.  See ISSUES.md #1.
  std::atomic<bool> gameFinished{false};
  std::atomic<bool> gameThreadDone{false};
  uint64_t frameCount = 0;
  // Set once PS1_VRAM_DUMP_FRAME has been honoured, so the shutdown dump does
  // not overwrite the requested frame -- both write PS1_VRAM_DUMP_PATH, and
  // the shutdown VRAM is exactly the freshly-cleared state we are avoiding.
  bool frameDumpWritten = false;

  // Initialize dispatch table before starting the game
  recomp_init_dispatch_table();
  fmt::print("[Dispatch] Table initialized.\n");

  // BSS mirror addresses (per-game polling slots)
  // Phase 2.2 retired the per-game VBlank counter BSS slot in favor of
  // `psyq_state().vsyncCounter` (atomic).  PsyQ HLE reads the singleton.
  // BUT: recompiled native MIPS code can poll the legacy BSS address
  // directly (`MEM_READ32(0x801CF2CC)` in Rayman) -- without a write-
  // through, those polls observe 0 forever and the game thread spins.
  //
  // `[bss_mirrors]` (TOML, optional) declares which BSS slots the VBlank
  // ticker should mirror.  When set, the thread does an atomic
  // `vsyncCounter` bump AND a `mem.write32(addr, counter)` so legacy
  // polling continues to work with the current architecture.
  uint32_t vblankCounterMirror = 0;
  uint32_t cdSyncMirror = 0;
  uint32_t cdReadyMirror = 0;
  if (!config_path.empty()) {
    try {
      auto cfg = toml::parse(config_path);
      if (cfg.contains("bss_mirrors")) {
        auto &mirrors = toml::find(cfg, "bss_mirrors");
        if (mirrors.is_table()) {
          auto readAddr = [&](const char *key) -> uint32_t {
            if (!mirrors.contains(key))
              return 0;
            auto v = toml::find(mirrors, key);
            if (v.is_string())
              return std::strtoul(v.as_string().c_str(), nullptr, 0);
            if (v.is_integer())
              return static_cast<uint32_t>(v.as_integer());
            return 0;
          };
          vblankCounterMirror = readAddr("vblank_counter");
          cdSyncMirror = readAddr("cd_sync_byte");
          cdReadyMirror = readAddr("cd_ready_byte");
          if (vblankCounterMirror != 0)
            fmt::print("[bss_mirrors] vblank_counter = 0x{:08X}\n",
                       vblankCounterMirror);
          if (cdSyncMirror != 0)
            fmt::print("[bss_mirrors] cd_sync_byte   = 0x{:08X}\n",
                       cdSyncMirror);
          if (cdReadyMirror != 0)
            fmt::print("[bss_mirrors] cd_ready_byte  = 0x{:08X}\n",
                       cdReadyMirror);
        }
      }
    } catch (const std::exception &) {
      // Optional section -- silent fallback.
    }
  }
  bios.setBssMirrors(cdSyncMirror, cdReadyMirror);

  // VBlank ticker thread
  // The game spins polling psyq_state().vsyncCounter (and PsyQ HLE wraps
  // VSync to read the same singleton).  This dedicated 60 Hz thread is
  // independent of SDL rendering, so the tick advances at the right rate
  // and the game's VSync wait exits quickly.
  //
  // Phase 3.2: this thread no longer calls `bios.triggerVBlankEvent()`
  // directly.  That call writes non-atomic state -- `drawSync.status[]`,
  // event-system flags, queued swap callback -- which was racing with the
  // game thread.  Instead we just bump the atomic counter and raise the
  // `vblankPending` flag; `hle_VSync`, running on the game thread, drains
  // the flag at the end of its wait and runs `triggerVBlankEvent` there.
  // `gpu.snapshotDisplayBuffer` and `bios.updatePadBuffers` stay here --
  // they own their own thread safety (renderer double-buffer / atomic
  // pad state) and are out of scope for 3.2.
  //
  // BSS mirror (`vblankCounterMirror`): when set via `[bss_mirrors]`, also
  // write-through to a PS1 RAM address so recompiled MIPS code that polls
  // the legacy slot directly keeps working -- see comment block above.
  std::thread vblankThread([&]() {
    using namespace std::chrono;
    const auto period = microseconds(16667); // ~60 Hz
    auto next = steady_clock::now() + period;
    while (!gameFinished.load(std::memory_order_acquire)) {
      std::this_thread::sleep_until(next);
      next += period;
      uint32_t newCount = ps1::psyq::psyq_state().vsyncCounter.fetch_add(
          1, std::memory_order_release) + 1;
      ps1::psyq::psyq_state().vblankPending.store(
          true, std::memory_order_release);
      if (vblankCounterMirror != 0) {
        memory.write32(vblankCounterMirror, newCount);
      }
      gpu.snapshotDisplayBuffer();
      bios.updatePadBuffers();
    }
  });

  // Launch game thread
  std::thread gameThread([&]() {
    // Identify ourselves so Bios::queueCdromEvent can inline-drain when
    // the IRQ callback fires synchronously from MIPS-driven port writes
    // on this thread.
    bios.setGameThreadId(std::this_thread::get_id());
    try {
      ctx.pc = entryPoint;
      recomp_dispatch(memory.ramPtr(), &ctx, entryPoint);
    } catch (const ps1::CpuException &e) {
      fmt::print("[Game] CPU Exception {} at PC=0x{:08X}\n",
                 static_cast<uint32_t>(e.cause), ctx.pc);
    } catch (const std::exception &e) {
      fmt::print("[Game] Exception: {}\n", e.what());
    } catch (...) {
      fmt::print("[Game] Unknown exception\n");
    }
    gameFinished.store(true, std::memory_order_release);
    gameThreadDone.store(true, std::memory_order_release);
  });

  bool running = true;
  while (running) {
    // 1. Poll SDL2 Events
    SDL_Event event;
    while (SDL_PollEvent(&event)) {
      switch (event.type) {
      case SDL_QUIT:
        running = false;
        break;
      case SDL_KEYDOWN:
        if (event.key.keysym.sym == SDLK_ESCAPE) {
          running = false;
        } else {
          mapKeyToButton(event.key.keysym.sym, input, true);
        }
        break;
      case SDL_KEYUP:
        mapKeyToButton(event.key.keysym.sym, input, false);
        break;
      }
    }

    // 2. Tick Hardware (per frame)
    // CDROM state machine
    cdromCtrl.tick(CYCLES_PER_FRAME);

    // Timers (263 scanlines per NTSC frame)
    uint32_t timerIrqs = 0;
    for (uint32_t scanline = 0; scanline < SCANLINES_PER_FRAME; scanline++) {
      timerIrqs |= timers.tick(CYCLES_PER_SCANLINE, true, false);
    }

    // Timer IRQs
    if (timerIrqs & ps1::IRQ_TMR0)
      irqCtrl.raiseInterrupt(ps1::IRQ_TMR0);
    if (timerIrqs & ps1::IRQ_TMR1)
      irqCtrl.raiseInterrupt(ps1::IRQ_TMR1);
    if (timerIrqs & ps1::IRQ_TMR2)
      irqCtrl.raiseInterrupt(ps1::IRQ_TMR2);

    // VBlank IRQ (once per frame)
    irqCtrl.raiseInterrupt(ps1::IRQ_VBLANK);

    // VBlank events (triggerVBlankEvent, snapshotDisplayBuffer, updatePadBuffers)
    // are now fired by the dedicated vblankThread above at a steady 60Hz,
    // so they run independently of the SDL render loop speed.

    // Other IRQs
    if (cdromCtrl.hasInterrupt()) {
      irqCtrl.raiseInterrupt(ps1::IRQ_CDROM);
      // Event triggering is now handled by the interrupt callback
      // (fired inline from pushResponse), so we only raise the HW IRQ here.
    }
    if (dma.hasInterrupt())
      irqCtrl.raiseInterrupt(ps1::IRQ_DMA);
    if (input.hasInterrupt()) {
      irqCtrl.raiseInterrupt(ps1::IRQ_PAD_MC);
      input.clearInterrupt();
    }
    if (spu.hasIrq()) {
      irqCtrl.raiseInterrupt(ps1::IRQ_SPU);
      spu.clearIrq();
    }

    // 3. Render
    if (!renderer.processEvents()) {
      running = false;
      continue;
    }
    renderer.renderFrame();

    frameCount++;
    ps1::metrics::count("frames");

    // Capture at a chosen frame, not only at shutdown: the game clears VRAM
    // every frame, so a shutdown-only dump always catches it freshly wiped.
    //
    // The threshold counts VBlanks, not iterations of this loop.  This loop is
    // paced by the SDL renderer's vsync and has been measured anywhere from 39
    // to 59 iterations per second depending on compositor load, while the game
    // thread advances on the steady 60 Hz vblankThread.  Anchoring on
    // frameCount therefore captured a different point of the intro on every
    // run -- sometimes the logo screen, sometimes the black gap after it --
    // which is what made the golden frame look non-deterministic.
    if (const char *atFrame = std::getenv("PS1_VRAM_DUMP_FRAME")) {
      const uint32_t vblanks =
          ps1::psyq::psyq_state().vsyncCounter.load(std::memory_order_acquire);
      if (!frameDumpWritten && vblanks >= std::strtoul(atFrame, nullptr, 10)) {
        const char *path = std::getenv("PS1_VRAM_DUMP_PATH");
        frameDumpWritten =
            dumpVramPpm(gpu, path ? path : "/tmp/vram_frame.ppm");
      }
    }

    // Status every 5 seconds
    if (frameCount % 300 == 0) {
      fmt::print("[Frame {}] I_STAT=0x{:04X} I_MASK=0x{:04X}\n", frameCount,
                 irqCtrl.readIStat(), irqCtrl.readIMask());
    }

    // Check if game thread ended
    if (gameFinished.load(std::memory_order_acquire)) {
      fmt::print("[Main] Game thread finished at frame {}\n", frameCount);
      running = false;
    }

    if (g_shutdown_requested) {
      fmt::print("[Main] Shutdown signal received at frame {}\n", frameCount);
      running = false;
    }

    // Frame pacing: SDL_GL_SetSwapInterval(1) provides VSync-based pacing
    // via the blocking SDL_GL_SwapWindow call in renderFrame().
    // No additional SDL_Delay needed -- it would double the frame time.
  }

  if (const char *vramDump = std::getenv("PS1_VRAM_DUMP_PATH")) {
    if (!frameDumpWritten)
      dumpVramPpm(gpu, vramDump);
  }
  gpu.publishMetrics();
  ps1::metrics::dumpJson();

  // Cleanup

  // Wait for game thread (with timeout)
  if (gameThread.joinable()) {
    gameFinished.store(true, std::memory_order_release); // shutdown signal
    auto deadline = std::chrono::steady_clock::now() + std::chrono::seconds(2);
    while (!gameThreadDone.load(std::memory_order_acquire) &&
           std::chrono::steady_clock::now() < deadline) {
      std::this_thread::sleep_for(std::chrono::milliseconds(10));
    }
    if (gameThreadDone.load(std::memory_order_acquire)) {
      gameThread.join(); // lambda returned -- safe to join
    } else {
      // Game thread is still inside `recomp_dispatch` (recompiled MIPS is a
      // tight polling loop that does not check `gameFinished`).  Detaching
      // and letting destructors run is UB -- the thread will be reading
      // `Bios::cdEventQueue_` etc. while we destruct them.  Skip C++
      // destructors entirely and exit immediately; the OS will reclaim
      // memory and SDL/audio handles.
      fmt::print("[Main] Game thread did not finish in 2s -- forcing exit "
                 "(skipping destructors to avoid UAF race)\n");
      fmt::print("Simulation ended after {} frames.\n", frameCount);
      gpu.publishMetrics();
      ps1::metrics::dumpJson();
      std::_Exit(0);
    }
  }

  // Join vblank ticker (gameFinished is already set above, so it will exit)
  if (vblankThread.joinable())
    vblankThread.join();

  if (audioDevice > 0) {
    SDL_CloseAudioDevice(audioDevice);
  }
  if (gamepad) {
    SDL_GameControllerClose(gamepad);
  }
  renderer.destroy();
  SDL_Quit();

  fmt::print("Simulation ended after {} frames.\n", frameCount);
  return 0;
}
