plugins {
    id "com.android.application"
}

android {
    namespace "com.gerisson.ps1recomp"
    compileSdk 35
    ndkVersion "27.2.12479018"

    defaultConfig {
        applicationId "com.gerisson.ps1recomp"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "0.1.0"

        ndk {
            abiFilters "arm64-v8a"
        }

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++20 -O2 -fno-rtti -ffunction-sections -fdata-sections"
                arguments "-DANDROID_STL=c++_static"
            }
        }
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    externalNativeBuild {
        cmake {
            path file("src/main/cpp/CMakeLists.txt")
            version "3.22.1"
        }
    }
}
