#pragma once

// ps1Runtime -- Runtime Macros
// These macros are emitted by InstructionEmitter and GteEmitter.
// They bridge recompiled C++ code -> runtime Memory/GTE subsystems.

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <runtime/cpu_context.h>
#include <runtime/memory.h>

// Memory Access Macros
// Used by InstructionEmitter for LB/LH/LW/SB/SH/SW

#define MEM_READ8(ctx, addr) (ctx)->mem->read8(addr)
#define MEM_READ16(ctx, addr) (ctx)->mem->read16(addr)
#define MEM_READ32(ctx, addr) (ctx)->mem->read32(addr)

#define MEM_WRITE8(ctx, addr, val) (ctx)->mem->write8(addr, val)
#define MEM_WRITE16(ctx, addr, val) (ctx)->mem->write16(addr, val)
#define MEM_WRITE32(ctx, addr, val) (ctx)->mem->write32(addr, val)

// Unaligned Load/Store
// Used for LWL/LWR/SWL/SWR instructions

inline uint32_t DO_LWL(recomp_context *ctx, uint32_t rt, uint32_t addr) {
  uint32_t aligned = addr & ~3u;
  uint32_t word = ctx->mem->read32(aligned);
  uint32_t shift = (addr & 3u);

  switch (shift) {
  case 0:
    return (rt & 0x00FFFFFF) | (word << 24);
  case 1:
    return (rt & 0x0000FFFF) | (word << 16);
  case 2:
    return (rt & 0x000000FF) | (word << 8);
  case 3:
    return word;
  default:
    return rt;
  }
}

inline uint32_t DO_LWR(recomp_context *ctx, uint32_t rt, uint32_t addr) {
  uint32_t aligned = addr & ~3u;
  uint32_t word = ctx->mem->read32(aligned);
  uint32_t shift = (addr & 3u);

  switch (shift) {
  case 0:
    return word;
  case 1:
    return (rt & 0xFF000000) | (word >> 8);
  case 2:
    return (rt & 0xFFFF0000) | (word >> 16);
  case 3:
    return (rt & 0xFFFFFF00) | (word >> 24);
  default:
    return rt;
  }
}

inline void DO_SWL(recomp_context *ctx, uint32_t rt, uint32_t addr) {
  uint32_t aligned = addr & ~3u;
  uint32_t word = ctx->mem->read32(aligned);
  uint32_t shift = (addr & 3u);

  switch (shift) {
  case 0:
    word = (word & 0xFFFFFF00) | (rt >> 24);
    break;
  case 1:
    word = (word & 0xFFFF0000) | (rt >> 16);
    break;
  case 2:
    word = (word & 0xFF000000) | (rt >> 8);
    break;
  case 3:
    word = rt;
    break;
  }
  ctx->mem->write32(aligned, word);
}

inline void DO_SWR(recomp_context *ctx, uint32_t rt, uint32_t addr) {
  uint32_t aligned = addr & ~3u;
  uint32_t word = ctx->mem->read32(aligned);
  uint32_t shift = (addr & 3u);

  switch (shift) {
  case 0:
    word = rt;
    break;
  case 1:
    word = (word & 0x000000FF) | (rt << 8);
    break;
  case 2:
    word = (word & 0x0000FFFF) | (rt << 16);
    break;
  case 3:
    word = (word & 0x00FFFFFF) | (rt << 24);
    break;
  }
  ctx->mem->write32(aligned, word);
}

// GTE Register Access
// Used by GteEmitter for MFC2/MTC2/CFC2/CTC2

inline uint32_t gte_read_data(ps1::CPUContext *ctx, uint8_t reg) {
  return ctx->cop2d[reg & 0x1F];
}

inline void gte_write_data(ps1::CPUContext *ctx, uint8_t reg, uint32_t val) {
  ctx->cop2d[reg & 0x1F] = val;
}

inline uint32_t gte_read_control(ps1::CPUContext *ctx, uint8_t reg) {
  return ctx->cop2c[reg & 0x1F];
}

inline void gte_write_control(ps1::CPUContext *ctx, uint8_t reg, uint32_t val) {
  ctx->cop2c[reg & 0x1F] = val;
}

// Control flow and System macros
#define BREAK(ctx) throw ps1::CpuException(ps1::ExceptionCause::Bp)

// SYSCALL: EnterCritical ($a0=1) returns old SR IE bit in $v0,
//          ExitCritical  ($a0=2) is a NOP in HLE.
#define SYSCALL(ctx)                                                           \
  do {                                                                         \
    if ((ctx)->r4 == 1) { /* EnterCritical */                                  \
      (ctx)->r2 = (ctx)->cop0[ps1::COP0_SR] & 0x404;                          \
      (ctx)->cop0[ps1::COP0_SR] &= ~0x404u;                                   \
    } else if ((ctx)->r4 == 2) { /* ExitCritical */                            \
      (ctx)->cop0[ps1::COP0_SR] |= 0x404u;                                    \
    }                                                                          \
  } while (0)

// Forward declaration -- generated by ps1Recomp in recompiled_out.cpp
void recomp_dispatch(uint8_t *rdram, recomp_context *ctx, uint32_t addr);

// Indirect-call diagnostic -- gated on `PS1_INDIRECT_TRACE=1`.  Cached at
// first use so the fast path is a single load+branch.  When a non-zero
// `PS1_INDIRECT_TRACE_RA=0x...` is set, only calls whose return address
// (r31) matches the filter are logged -- surgical inspection of one call
// site instead of drowning in every indirect call in the binary.
namespace ps1_dbg {
inline bool indirect_trace_enabled() {
  static const bool v = []() {
    const char *e = std::getenv("PS1_INDIRECT_TRACE");
    return e && std::strcmp(e, "0") != 0 && e[0] != '\0';
  }();
  return v;
}
inline uint32_t indirect_trace_ra_filter() {
  static const uint32_t f = []() {
    const char *e = std::getenv("PS1_INDIRECT_TRACE_RA");
    return e ? static_cast<uint32_t>(std::strtoul(e, nullptr, 0)) : 0u;
  }();
  return f;
}
} // namespace ps1_dbg

#define PS1_INDIRECT_TRACE_HOOK(ctx, addr)                                     \
  do {                                                                         \
    if (ps1_dbg::indirect_trace_enabled()) {                                   \
      uint32_t _ra_f = ps1_dbg::indirect_trace_ra_filter();                    \
      if (_ra_f == 0u || _ra_f == (ctx)->r[31]) {                              \
        std::fprintf(stderr, "[INDIRECT] RA=0x%08X -> 0x%08X\n",               \
                     (ctx)->r[31], static_cast<uint32_t>(addr));               \
      }                                                                        \
    }                                                                          \
  } while (0)

// Guest address of the most recent indirect jump or call site.
//
// The dispatcher prints this when a target cannot be resolved.  Neither of the
// other two clues is enough on its own: the guest `$ra` holds the return
// address of the last *direct* call, so it points somewhere unrelated on those
// paths, and the host stack names the emitted function but not which of its
// several indirect sites fired -- the GOOL interpreter alone has seven.
inline uint32_t &ps1LastIndirectSite() {
  static uint32_t site = 0;
  return site;
}

inline uint32_t &ps1LastIndirectTarget() {
  static uint32_t target = 0;
  return target;
}

#define PS1_SET_INDIRECT_SITE_TARGET(pc, addr)                                 \
  do {                                                                         \
    ps1LastIndirectSite() = (pc);                                              \
    ps1LastIndirectTarget() = static_cast<uint32_t>(addr);                     \
  } while (0)

#define CALL_INDIRECT_AT(ctx, addr, pc)                                        \
  do {                                                                         \
    PS1_SET_INDIRECT_SITE_TARGET(pc, addr);                                    \
    CALL_INDIRECT(ctx, addr);                                                  \
  } while (0)
#define JUMP_INDIRECT_AT(ctx, addr, pc)                                        \
  do {                                                                         \
    PS1_SET_INDIRECT_SITE_TARGET(pc, addr);                                    \
    JUMP_INDIRECT(ctx, addr);                                                  \
  } while (0)

#define CALL_INDIRECT(ctx, addr)                                               \
  do {                                                                         \
    PS1_INDIRECT_TRACE_HOOK(ctx, addr);                                        \
    recomp_dispatch(rdram, ctx, static_cast<uint32_t>(addr));                  \
  } while (0)
#define JUMP_INDIRECT(ctx, addr)                                               \
  do {                                                                         \
    PS1_INDIRECT_TRACE_HOOK(ctx, addr);                                        \
    recomp_dispatch(rdram, ctx, static_cast<uint32_t>(addr));                  \
    return;                                                                    \
  } while (0)
// Same dispatch, but the emitter tests $ra afterwards: the block being jumped
// into ends in `jr $ra`, and the calling function has pointed $ra back into
// itself, so control resumes there instead of unwinding to the caller.
#define JUMP_INDIRECT_RESUME(ctx, addr)                                        \
  do {                                                                         \
    PS1_INDIRECT_TRACE_HOOK(ctx, addr);                                        \
    recomp_dispatch(rdram, ctx, static_cast<uint32_t>(addr));                  \
  } while (0)
#define JUMP_INDIRECT_RESUME_AT(ctx, addr, pc)                                 \
  do {                                                                         \
    PS1_SET_INDIRECT_SITE_TARGET(pc, addr);                                    \
    JUMP_INDIRECT_RESUME(ctx, addr);                                           \
  } while (0)
#define COP0_RFE(ctx) /* NOP for now */
